/*
  4x4 Evolution text formats and models, from synthetic files written line by line.
*/
import test from "node:test";
import assert from "node:assert/strict";
import {
  evoTrackTypeName, isEvoSit, isEvoTrk, isSmfModel, parseEvoLvl, parseEvoSit, parseEvoTex, parseEvoTrk,
  parseEvoVeg, parseEvoWat, parseSmf, smfTextureReference, truckManifestLines,
} from "../src/index.ts";
import { latin1 } from "./fixtures/build.ts";

const text = (lines: string[]) => latin1(lines.join("\r\n") + "\r\n");

test("SIT v6: header, boxes by label, vehicles, courses", () => {
  const sit = parseEvoSit(text([
    "version", "6", "ASPEN.LVL",
    "!Race Track Name", "Silverton Pass", "authorName", "TRI", "Track Race Type", "2",
    "ambient sound,track length,weather mask", "3,1200,7",
    "*** Boxes ***", "2",
    "Box 1 of 2 ---", "wPos", "10,20,30", "wOrient", "0,0,1.5", "model", "TREE.SMF", "mass", "100",
    "@sound effect entries", "", "", "!type,flags", "10,4", "bvel", "70,0,0", "%castShadowOnMe", "1",
    "Box 2 of 2 ---", "wPos", "1,2,3", "#parent", "1",
    "*** Vehicles ***", "1", "Vehicle 1 of 1 ---", "staticName", "CBLS24.TRK", "wPos", "5,6,7", "wOrient", "0,0,3.14",
    "*** Course ***", "***************** 1", "cstart", "0,0,0", "cend", "1,0,0", "&cSpeedLimit,cTrackWidth", "50,20",
    "***************** 2", "cstart", "1,0,0", "cend", "2,0,0",
  ]), "TEST.SIT");
  assert.equal(sit.version, 6);
  assert.equal(sit.game, 1);
  assert.equal(sit.lvlName, "ASPEN.LVL");
  assert.equal(sit.trackName, "Silverton Pass");
  assert.equal(sit.raceType, 2);
  assert.equal(evoTrackTypeName(sit.raceType), "CIRCUIT");
  assert.deepEqual([sit.ambientSound, sit.trackLength, sit.weatherMask], [3, 1200, 7]);
  assert.equal(sit.boxes.length, 2);
  const [tree, child] = sit.boxes;
  assert.deepEqual(tree.position, [10, 20, 30]);
  assert.deepEqual(tree.orient, [0, 0, 1.5]);
  assert.equal(tree.modelName, "TREE.SMF");
  // The two empty lines after "sound effect entries" do not desynchronize the record.
  assert.equal(tree.boxType, 10);
  assert.equal(tree.boxFlags, 4);
  assert.deepEqual(tree.bvel, [70, 0, 0]);
  assert.equal(tree.castShadowOnMe, true);
  assert.equal(tree.instanceId, 1);
  assert.equal(child.parent, 1);
  assert.equal(sit.vehicles[0].name, "CBLS24.TRK");
  assert.deepEqual(sit.courses[0].segments.map((s) => s.end), [[1, 0, 0], [2, 0, 0]]);
  assert.equal(sit.courses[0].segments[0].speedLimit, 50);
  assert.deepEqual(sit.warnings, []);
});

test("SIT v7: brace instances driven by their field comments", () => {
  const sit = parseEvoSit(text([
    "version", "7", "PEAK.LVL",
    "*** Boxes ***", "// boxTypeList", "1", "CCollide 3", "// boxCount", "1", "// Box data list",
    "{ 42 CCollide", '    ""                    // name', '    "SK1PEIR.SMF"         // staticName',
    "    41.1,24.4,200         // size", "    1,2,3                 // wPos", "    0,0,0.5               // wOrient",
    "    7                     // someNewField", "} CCollide",
  ]), "PEAK.SIT");
  assert.equal(sit.game, 2);
  const [box] = sit.boxes;
  assert.equal(box.sourceClass, "CCollide");
  assert.equal(box.schemaVersion, 3);
  assert.equal(box.instanceId, 42);
  assert.equal(box.modelName, "SK1PEIR.SMF");
  assert.deepEqual(box.size, [41.1, 24.4, 200]);
  assert.equal(box.sourceFields?.someNewField, "7");
});

test("isEvoSit tells an Evo scene script from an MTM one", () => {
  assert.equal(isEvoSit(text(["version", "7", "X.LVL"])), true);
  assert.equal(isEvoSit(text(["SUMMIT1.LVL", "..."])), false);
});

test("LVL: positional head, labelled environment, unknown lines kept", () => {
  const lvl = parseEvoLvl(text([
    "// .LVL version", "1", "0", "peak.raw", "peak.clr", "peak.tex", "sky.raw", "wind.wav",
    "!waterHeight,waterTideHeight,waterTidePeriod", "90,2,30", "@waterR,waterG,waterB,waterOpacity", "10,20,30,128",
    "#detailTexture", "detail.raw", "$lightSourceVector", "0,-1,0", "signature: X // WARNING: Do not edit this file",
  ]), "PEAK.LVL");
  assert.equal(lvl.heightName, "peak.raw");
  assert.equal(lvl.texName, "peak.tex");
  assert.equal(lvl.water.height, 90);
  assert.deepEqual(lvl.water.color, [10, 20, 30, 128]);
  assert.equal(lvl.detailTexture, "detail.raw");
  assert.deepEqual(lvl.lightVector, [0, -1, 0]);
  assert.equal(lvl.trailing.length, 1);
});

test("WAT: labels on their own lines", () => {
  const wat = parseEvoWat(text(["VERSION", "1", "BASE NAME", "water", "CYCLE SPEED", "0.5", "0.25", "SCALE", "32", "64", "SPEC ALPHA", "0.8"]), "X.WAT");
  assert.deepEqual([wat.baseName, wat.cycleSpeed, wat.scale, wat.specularAlpha], ["water", [0.5, 0.25], [32, 64], 0.8]);
});

test("TEX: ordinary and shadow groups kept apart", () => {
  const tex = parseEvoTex(text(["Version", "1", "textureCount,shadowTextureCount", "2,1", "0,0,A.RAW", "100,1,B.RAW", "0,3,S.RAW"]), "X.TEX");
  assert.deepEqual(tex.ordinary.map((r) => r.name), ["A.RAW", "B.RAW"]);
  assert.deepEqual(tex.shadow, [{ param0: 0, param1: 3, name: "S.RAW" }]);
  assert.deepEqual(tex.warnings, []);
  assert.equal(parseEvoTex(text(["Version", "1", "c", "3,0", "0,0,A.RAW"]), "Y.TEX").warnings.length, 1);
});

test("VEG: header, then counted tree grids", () => {
  const veg = parseEvoVeg(text([
    "Version", "6", "maxTrees", "100", "treeModel", "a.smf", "b.smf", "c.smf", "d.smf", "treeTex", "pine.raw",
    "treeGrid", "2", "1,2,3,200", "4,5,6,7", "treeGrid", "0", "treeGrid", "1", "9,9,9,1",
  ]), "X.VEG");
  assert.equal(veg.maxTrees, 100);
  assert.deepEqual(veg.treeModels, ["A.SMF", "B.SMF", "C.SMF", "D.SMF"]);
  assert.equal(veg.treeTexture, "PINE.RAW");
  assert.equal(veg.gridCount, 3);
  assert.deepEqual(veg.trees.map((t) => t.value), [200, 7, 1]);
});

const SMF = text([
  "C3DModel", "4", "2", "1,500",
  "OPAQUE", "1", "3", "3,2,1,info",
  "1,1,32,0,1,BODY.RAW",
  "1,2,3,0,1,0,0.25,0.75", "4,5,6,0,1,0,0.5,0.5", "7,8,9,0,1,0,1,0",
  "10,20,30,0,1,0,0.25,0.75", "40,50,60,0,1,0,0.5,0.5", "70,80,90,0,1,0,1,0",
  "0,1,2",
  "TRANSPL", "0", "3", "3,1,2,",
  "v1", "1,0.25,32,1,0,NULL.TIF", '"glass_bump.tif"',
  "0,0,0,0,0,1,0,0", "1,0,0,0,0,1,1,0", "0,1,0,0,0,1,0,1",
  "0,1,2", "0,1,9",
]);

test("SMF: Evo axes and file winding as written, every frame kept", () => {
  assert.equal(isSmfModel(SMF), true);
  const smf = parseSmf(SMF, "TEST.SMF");
  assert.deepEqual([smf.fileVersion, smf.lodEnabled, smf.lodSwitchHeight], [4, true, 500]);
  const [opaque, glass] = smf.groups;
  assert.equal(opaque.frames.length, 2);
  assert.ok(opaque.frames[0].positions instanceof Float64Array);
  assert.deepEqual([...opaque.frames[0].positions.subarray(0, 3)], [1, 2, 3]);
  assert.deepEqual([...opaque.frames[1].positions.subarray(6, 9)], [70, 80, 90]);
  assert.deepEqual([...opaque.frames[0].uvs.subarray(0, 2)], [0.25, 0.75]);
  assert.deepEqual([...opaque.indices], [0, 1, 2]);
  assert.equal(opaque.objectInfo, "info");
  assert.equal(opaque.material.textureName, "BODY.RAW");
  assert.equal(opaque.material.reflective, true);
  assert.equal(glass.visible, false);
  assert.equal(glass.lodGroup, true);
  assert.equal(glass.material.bumpForm, true);
  assert.equal(glass.material.transparent, true);
  assert.equal(smfTextureReference(glass.material.textureName), null);
  assert.equal(smfTextureReference(glass.material.bumpTextureName), "GLASS_BUMP.TIF");
  // The face indexing vertex 9 is dropped with a warning; the declared count is kept.
  assert.equal(glass.faceCount, 2);
  assert.deepEqual([...glass.indices], [0, 1, 2]);
  assert.equal(smf.warnings.length, 1);
});

test("SMF: refusals", () => {
  assert.throws(() => parseSmf(text(["NotAModel"]), "X"), /not a C3DModel/);
  assert.throws(() => parseSmf(text(["C3DModel", "9", "0"]), "X"), /unsupported .SMF version 9/);
  assert.throws(() => parseSmf(text(["C3DModel", "2", "1", "G", "1", "1", "3,1,0,", "1,1,1,0,0,T", "0,0,0"]), "X"), /truncated vertex block/);
});

test("TRK v7: counted lists, vec3 anchors, uncounted scrape points, lights, colors", () => {
  const bytes = latin1([
    "version", "7", "truckName", "Blazer", "truckModelBaseName", "trblaz", "axleModelName", "NULL.BIN",
    "faxle.rtire.static_bpos", "+2.385,-0.700,+5.360", "xm.maxGear", "3", "xm.gear_ratio[] 1st/2nd/3rd", "3.5", "-0", "1.2",
    "numColors", "1", "colorList[]", "0.5,0.5,0.5,200.4,300,-3,NULL", "sc[].pt", "1,2,3", "4,5,6",
    "Wave File", "a.wav", "b.wav", "Number of Lights", "1", "Light 0 type", "2", "Light 0 body axis pos (x,y,z,r)", "1,2,3,0.5",
    "truckMake", "Chevrolet", "someNumber", "12.5", "\u001a", "signature: C89BC44E D3A8FB4D // WARNING: Do not edit this file",
  ].join("\r\n") + "\0\0");
  assert.equal(isEvoTrk(bytes), true);
  const trk = parseEvoTrk(bytes, "BLAZER.TRK");
  assert.equal(trk.game, 2);
  assert.equal(trk.truckModelBaseName, "trblaz");
  assert.equal(trk.tireModelBaseName, null);
  assert.deepEqual(trk.wheelAnchors["faxle.rtire.static_bpos"], { x: 2.385, y: -0.7, z: 5.36 });
  assert.deepEqual(trk.specs["xm.gear_ratio[]"], [3.5, -0, 1.2]);
  assert.equal(trk.colors[0].red, 200.4);
  assert.deepEqual(trk.scrapePoints, [{ x: 1, y: 2, z: 3 }, { x: 4, y: 5, z: 6 }]);
  assert.deepEqual(trk.waveFiles, ["a.wav", "b.wav"]);
  assert.equal(trk.numberOfLights, 1);
  assert.deepEqual(trk.lights[0], { index: 0, type: 2, pos: { x: 1, y: 2, z: 3 }, bitmapRadius: 0.5 });
  assert.equal(trk.specs.truckMake, "Chevrolet");
  assert.equal(trk.specs.someNumber, 12.5);
  assert.equal(trk.signature, "C89BC44E D3A8FB4D");
  assert.equal(trk.fieldOrder.indexOf("xm.gear_ratio[]") > trk.fieldOrder.indexOf("xm.maxGear"), true);
  assert.throws(() => parseEvoTrk(latin1("MTM2 truckName\r\nBigfoot"), "X"), /not an Evo TRK/);
});

test("truckManifestLines drops NUL padding and the DOS EOF marker, and splits any line ending", () => {
  assert.deepEqual(truckManifestLines(latin1("a\r\nb\rc\n\u001a\n  d  \0\0")), ["a", "b", "c", "d"]);
});
