import { splitEvoLines, evoLabel, evoNumbers } from "./text.ts";

/** A parsed Evo .LVL: the terrain manifest and environment record. */
export interface EvoLvl {
  version: number;
  sourceName: string;
  /** The 16-bit height grid (.RAW). */
  heightName: string;
  /** The 16-bit terrain tile-index grid (.CLR). */
  clrName: string;
  /** The terrain and shadow texture table (.TEX). */
  texName: string;
  skyName: string;
  ambientWav: string;
  water: { height: number; tideHeight: number; tidePeriod: number; color: number[] };
  detailTexture: string | null;
  lightVector: number[] | null;
  vegTexture: string | null;
  /** Lines after the head that match no known label, kept verbatim. */
  trailing: string[];
}

/** A parsed Evo 2 .WAT animated-water material. */
export interface EvoWat {
  sourceName: string;
  version: number;
  baseName: string | null;
  cycleSpeed: [number, number];
  scale: [number, number];
  specularAlpha: number;
}

/*
  Evo .LVL v1: the terrain manifest and environment record.

    // .LVL version
    1
    0
    <track>.raw          16-bit height grid
    <track>.clr          16-bit terrain tile-index grid
    <track>.tex          terrain and shadow texture table
    <sky>.raw
    <ambient>.wav
    !waterHeight,waterTideHeight,waterTidePeriod
    @waterR,waterG,waterB,waterOpacity
    #detailTexture
    $lightSourceVector
    %vegTexture

  The first five payload lines are positional and the rest are label-driven, so the reader
  takes the head by index and then walks label/value pairs to the end. Some Evo 1 stock
  levels append a `signature: ... // WARNING: Do not edit this file` line; it matches no
  label and is kept as trailing metadata rather than being treated as a parse failure.

  This is emphatically NOT the MTM/TV-family .LVL schema the viewer already reads, where
  line 4 is a global .ACT and lines 14-21 are music/fog/light values. Evo has no track-wide
  palette at all: every indexed image resolves its own same-stem .ACT.

  Ported from JSTrackViewer's src/worker/evo/evo-lvl-parser.js (identical in JSMTM2Converter).
*/

const LVL_HEAD_LINES = 3;   // "// .LVL version", version, and the unidentified 0

export function parseEvoLvl(bytes: Uint8Array, sourceName: string): EvoLvl {
  const lines = splitEvoLines(bytes);
  const version = Number.parseInt((lines[1] ?? "").trim(), 10);
  if (!Number.isFinite(version)) throw new Error(`${sourceName}: unreadable .LVL version line`);

  const lvl: EvoLvl = {
    version,
    sourceName,
    heightName: (lines[LVL_HEAD_LINES + 0] ?? "").trim(),
    clrName:    (lines[LVL_HEAD_LINES + 1] ?? "").trim(),
    texName:    (lines[LVL_HEAD_LINES + 2] ?? "").trim(),
    skyName:    (lines[LVL_HEAD_LINES + 3] ?? "").trim(),
    ambientWav: (lines[LVL_HEAD_LINES + 4] ?? "").trim(),
    water: { height: 0, tideHeight: 0, tidePeriod: 0, color: [255, 255, 255, 0] },
    detailTexture: null,
    lightVector: null,
    vegTexture: null,
    trailing: [],
  };

  for (let i = LVL_HEAD_LINES + 5; i < lines.length; i++) {
    const label = evoLabel(lines[i]);
    if (!label) continue;
    const value = lines[i + 1] ?? "";

    if (label === "waterHeight,waterTideHeight,waterTidePeriod") {
      const [height, tideHeight, tidePeriod] = evoNumbers(value);
      lvl.water.height = height ?? 0;
      lvl.water.tideHeight = tideHeight ?? 0;
      lvl.water.tidePeriod = tidePeriod ?? 0;
      i++;
    } else if (label === "waterR,waterG,waterB,waterOpacity") {
      const rgba = evoNumbers(value);
      if (rgba.length === 4) lvl.water.color = rgba;
      i++;
    } else if (label === "detailTexture") {
      lvl.detailTexture = value.trim() || null;
      i++;
    } else if (label === "lightSourceVector") {
      const vector = evoNumbers(value);
      if (vector.length === 3) lvl.lightVector = vector;
      i++;
    } else if (label === "vegTexture") {
      lvl.vegTexture = value.trim() || null;
      i++;
    } else {
      lvl.trailing.push(lines[i].trim());
    }
  }
  return lvl;
}

/*
  Evo 2 .WAT v1, the optional animated-water material.

    VERSION / 1 / BASE NAME / <stem> / CYCLE SPEED / u / v / SCALE / u / v / SPEC ALPHA / a

  Labels are upper-case words on their own lines and the two-value records put each value on
  its own line rather than comma-separating them, so this is read positionally after the
  label rather than through the shared label/value walk.
*/
export function parseEvoWat(bytes: Uint8Array, sourceName: string): EvoWat {
  const lines = splitEvoLines(bytes).map((line) => line.trim());
  const wat: EvoWat = { sourceName, version: 1, baseName: null, cycleSpeed: [0, 0], scale: [64, 64], specularAlpha: 0 };
  for (let i = 0; i < lines.length; i++) {
    const label = lines[i].toUpperCase();
    if (label === "VERSION") wat.version = Number.parseInt(lines[i + 1] ?? "1", 10) || 1;
    else if (label === "BASE NAME") wat.baseName = lines[i + 1] || null;
    else if (label === "CYCLE SPEED") wat.cycleSpeed = [num(lines[i + 1]), num(lines[i + 2])];
    else if (label === "SCALE") wat.scale = [num(lines[i + 1]) || 64, num(lines[i + 2]) || 64];
    else if (label === "SPEC ALPHA") wat.specularAlpha = num(lines[i + 1]);
  }
  return wat;
}

function num(value: string | undefined): number {
  const parsed = Number.parseFloat((value ?? "").trim());
  return Number.isFinite(parsed) ? parsed : 0;
}
