/*
  4x4 Evolution vehicle manifests: TRK version 6 (Evo 1) and version 7 (Evo 2).

    version
    6                                   6 = 4x4 Evolution, 7 = 4x4 Evolution 2
    truckName
    Chevrolet Blazer TrailBlazer 4WD
    ...
    signature: C89BC44E D3A8FB4D // WARNING: Do not edit this file

  It is the same line-oriented label/value text MTM2 uses, with a version header instead of an
  "MTM2" one, and three differences that matter to a reader:

    - Wheel anchors are ONE vec3 line ("faxle.rtire.static_bpos" -> "+2.385,-0.700,+5.360").
      MTM2 splits the same data into three ".x"/".y"/".z" label/value pairs.
    - Models are .SMF, not .BIN, and the manifest names bare stems ("trblaz", "TrailBlazer").
    - Several fields are counted lists: a "<label>[]" line followed by N bare value lines.
      Where the count lives in an earlier field it is used; "sc[].pt" has no count anywhere,
      so its run is read until a line stops looking like a vec3, which is unambiguous because
      every label that can follow it is non-numeric. "xm.gear_ratio[]" is the one list label
      carrying a trailing gear-name comment, and the comment changes with the gear count, so
      it is matched on everything up to the "[]".

  Verified against every manifest in both stock TRUCK.PODs: 121 v6 files and 150 v7 files,
  each read to its signature line with no list value mistaken for a label.

  Evo has no axle model, axle bars, driveshaft or instrument cluster: axleModelName is
  "NULL.BIN" and barTextureName "NULL.RAW" in all 271 stock manifests. Positions are in feet,
  the unit MTM2 uses.

  Consolidated from JSTruckViewer's src/worker/evo/evo-trk-parser.js and JSMTM2Converter's
  src/formats/evo/evo-trk-parser.js, which read identically and differed only in the shape they
  returned. This returns everything either kept, as written: absent fields are null, and paint
  swatch channels are not rounded.
*/
import { truckManifestLines, type Vec3 } from "../truck/common.ts";

export { truckManifestLines };

export interface EvoTrkLight {
  index: number;
  type?: number;
  pos?: Vec3;
  bitmapRadius?: number;
  heading?: number;
  pitch?: number;
  spinSpeed?: number;
  coneLength?: number;
  coneBaseRadius?: number;
  coneRimRadius?: number;
  coneTexture?: string;
  sourceBitmap?: string;
  msOn?: number;
  msOff?: number;
}

/*
  A paint scheme: an HSV shift, the RGB swatch the Evo garage shows for it, and a decal
  texture. Every entry in both stock archives names "NULL" for that texture.
*/
export interface EvoTrkColor {
  hue: number;
  saturation: number;
  brightness: number;
  /** Swatch channels as written (not rounded or clamped). */
  red: number;
  green: number;
  blue: number;
  textureName: string;
}

/** Any value in `specs`: a number, a number tuple, text, or a counted numeric list. */
export type EvoTrkSpec = number | number[] | string;

export interface EvoTrk {
  sourceName: string;
  /** 6 or 7. */
  version: number;
  /** 1 for 4x4 Evolution, 2 for 4x4 Evolution 2. */
  game: 1 | 2;
  truckName: string;
  truckModelBaseName: string | null;
  tireModelBaseName: string | null;
  axleModelName: string | null;
  shockTextureName: string | null;
  barTextureName: string | null;
  axlebarOffset: Vec3 | null;
  driveshaftPos: Vec3 | null;
  /** Keyed by the manifest labels in EVO_WHEEL_KEYS. */
  wheelAnchors: Record<string, Vec3>;
  scrapePoints: Vec3[];
  instrumentCluster: string | null;
  numberOfLights: number | null;
  lights: EvoTrkLight[];
  colors: EvoTrkColor[];
  stockParts: string[];
  waveFiles: string[];
  /**
   * Every other label/value pair: scalars as numbers, comma tuples as number arrays, text as
   * text (truckMake, truckModel, truckClass and teamRequirement always stay text). Counted
   * numeric lists are stored under their "<name>[]" label.
   */
  specs: Record<string, EvoTrkSpec>;
  signature: string;
  /** The raw value line of each scalar label/value pair, including the named fields above. */
  rawValues: Record<string, string>;
  /** Scalar labels and counted-list labels ("<name>[]") in file order, repeats included. */
  fieldOrder: string[];
}

const EVO_VERSIONS: Record<number, 1 | 2> = { 6: 1, 7: 2 };

const COUNTED_LISTS: Record<string, string> = {
  "xm.gear_ratio[]": "xm.maxGear",
  "xm.gearInertia[]": "xm.maxGear",
  "eng.torqueTable[]": "eng.torqueTableCount",
  "stockPartList[]": "numStockParts",
  "colorList[]": "numColors",
};

/** The four wheel-anchor labels, front right, front left, rear right, rear left. */
export const EVO_WHEEL_KEYS = [
  "faxle.rtire.static_bpos",
  "faxle.ltire.static_bpos",
  "raxle.rtire.static_bpos",
  "raxle.ltire.static_bpos",
] as const;

const WHEEL_KEY_SET = new Set<string>(EVO_WHEEL_KEYS);
const NAMED_STRINGS = ["truckModelBaseName", "tireModelBaseName", "axleModelName", "shockTextureName", "barTextureName"] as const;
const NAMED_STRING_SET = new Set<string>(NAMED_STRINGS);
const TEXT_SPECS = new Set(["truckMake", "truckModel", "truckClass", "teamRequirement"]);

/** True when these lines open with the Evo "version" / 6|7 pair rather than an MTM header. */
export function isEvoTrkLines(lines: readonly string[]): boolean {
  return (lines[0] ?? "").trim().toLowerCase() === "version" && Number.parseInt(lines[1] ?? "", 10) in EVO_VERSIONS;
}

/** True when these bytes are an Evo TRK. */
export function isEvoTrk(bytes: Uint8Array): boolean {
  return isEvoTrkLines(truckManifestLines(bytes.subarray(0, 64)));
}

/**
 * Parse an Evo TRK.
 *
 * @throws Error when the bytes are not an Evo manifest.
 */
export function parseEvoTrk(bytes: Uint8Array, sourceName: string): EvoTrk {
  return parseEvoTrkLines(truckManifestLines(bytes), sourceName);
}

/** Parse an Evo TRK already split by `truckManifestLines`. */
export function parseEvoTrkLines(lines: readonly string[], sourceName: string): EvoTrk {
  if (!isEvoTrkLines(lines)) throw new Error(`${sourceName}: not an Evo TRK (expected a "version" header of 6 or 7)`);
  const version = Number.parseInt(lines[1], 10);
  const trk: EvoTrk = {
    sourceName,
    version,
    game: EVO_VERSIONS[version],
    truckName: "",
    truckModelBaseName: null,
    tireModelBaseName: null,
    axleModelName: null,
    shockTextureName: null,
    barTextureName: null,
    axlebarOffset: null,
    driveshaftPos: null,
    wheelAnchors: {},
    scrapePoints: [],
    instrumentCluster: null,
    numberOfLights: null,
    lights: [],
    colors: [],
    stockParts: [],
    waveFiles: [],
    specs: {},
    signature: "",
    rawValues: {},
    fieldOrder: [],
  };
  const lights: (EvoTrkLight | null)[] = [];

  for (let i = 2; i < lines.length; i++) {
    const label = lines[i];
    if (label.startsWith("signature:")) {
      trk.signature = label.slice("signature:".length).split("//")[0].trim();
      continue;
    }

    if (label === "sc[].pt") {
      while (i + 1 < lines.length && isVec3(lines[i + 1])) trk.scrapePoints.push(vec3(lines[++i]));
      continue;
    }

    const listLabel = label.includes("[]") ? label.slice(0, label.indexOf("[]") + 2) : label;
    const countField = COUNTED_LISTS[listLabel];
    if (countField) {
      const count = Math.max(0, Math.trunc(Number(trk.specs[countField]) || 0));
      const values = lines.slice(i + 1, i + 1 + count);
      i += values.length;
      trk.fieldOrder.push(listLabel);
      if (listLabel === "colorList[]") trk.colors = values.map(colorEntry);
      else if (listLabel === "stockPartList[]") trk.stockParts = values.map((value) => value.trim());
      else trk.specs[listLabel] = values.map((value) => number(value));
      continue;
    }

    const value = lines[i + 1] ?? "";
    if (label === "Wave File") {
      trk.waveFiles.push(value);
      i++;
      // The one list whose length is neither counted nor bounded by a value shape: it ends at
      // the first line that is not a sound file name.
      while (i + 1 < lines.length && /\.wav$/i.test(lines[i + 1])) trk.waveFiles.push(lines[++i]);
      continue;
    }

    const lightMatch = label.match(/^Light (\d+) /);
    if (lightMatch) {
      applyLight(lights, Number.parseInt(lightMatch[1], 10), label.slice(lightMatch[0].length).trim(), value);
      i++;
      continue;
    }

    trk.rawValues[label] = value;
    trk.fieldOrder.push(label);
    i++;
    if (WHEEL_KEY_SET.has(label)) trk.wheelAnchors[label] = vec3(value);
    else if (label === "truckName") trk.truckName = value;
    else if (NAMED_STRING_SET.has(label)) trk[label as (typeof NAMED_STRINGS)[number]] = value;
    else if (label === "axlebarOffset" || label === "driveshaftPos") trk[label] = vec3(value);
    else if (label === "Instrument Cluster") trk.instrumentCluster = value;
    else if (label === "Number of Lights") trk.numberOfLights = Number.parseInt(value, 10) || 0;
    else trk.specs[label] = TEXT_SPECS.has(label) ? value : specValue(value);
  }

  trk.lights = lights.filter((light): light is EvoTrkLight => light !== null);
  return trk;
}

function applyLight(lights: (EvoTrkLight | null)[], index: number, property: string, value: string): void {
  while (lights.length <= index) lights.push(null);
  const light = (lights[index] ??= { index });
  const parts = value.split(",");
  if (property === "type") light.type = Number.parseInt(value, 10) || 0;
  else if (property.startsWith("body axis pos")) {
    light.pos = { x: number(parts[0]), y: number(parts[1]), z: number(parts[2]) };
    light.bitmapRadius = number(parts[3]);
  } else if (property.startsWith("heading")) {
    light.heading = number(parts[0]);
    light.pitch = number(parts[1]);
    light.spinSpeed = number(parts[2]);
  } else if (property.startsWith("cone:")) {
    light.coneLength = number(parts[0]);
    light.coneBaseRadius = number(parts[1]);
    light.coneRimRadius = number(parts[2]);
    light.coneTexture = (parts[3] ?? "").trim();
  } else if (property.startsWith("source:")) light.sourceBitmap = value.trim();
  else if (property.startsWith("ms on")) {
    light.msOn = Number.parseInt(parts[0], 10) || 0;
    light.msOff = Number.parseInt(parts[1], 10) || 0;
  }
}

function colorEntry(line: string): EvoTrkColor {
  const parts = line.split(",");
  return {
    hue: number(parts[0]),
    saturation: number(parts[1]),
    brightness: number(parts[2]),
    red: number(parts[3]),
    green: number(parts[4]),
    blue: number(parts[5]),
    textureName: (parts[6] ?? "").trim(),
  };
}

function isVec3(line: string): boolean {
  const parts = line.split(",");
  return parts.length === 3 && parts.every((part) => Number.isFinite(Number.parseFloat(part)));
}

function vec3(value: string): Vec3 {
  const parts = String(value).split(",");
  return { x: number(parts[0]), y: number(parts[1]), z: number(parts[2]) };
}

function number(value: string | undefined): number {
  const parsed = Number.parseFloat(String(value ?? "").trim());
  return Number.isFinite(parsed) ? parsed : 0;
}

/** Scalars stay numbers, comma tuples become number arrays, anything else stays text. */
export function trkSpecValue(value: string): EvoTrkSpec {
  const trimmed = String(value).trim();
  if (!trimmed) return "";
  const parts = trimmed.split(",");
  if (parts.every((part) => /^[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$/.test(part.trim()))) {
    return parts.length === 1 ? number(parts[0]) : parts.map((part) => number(part));
  }
  return trimmed;
}

const specValue = trkSpecValue;
